/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SetupLazyImport = createFileRoute('/setup')()
const InitialsyncLazyImport = createFileRoute('/initialsync')()
const CollectionLazyImport = createFileRoute('/collection')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SetupLazyRoute = SetupLazyImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/setup.lazy').then((d) => d.Route))

const InitialsyncLazyRoute = InitialsyncLazyImport.update({
  id: '/initialsync',
  path: '/initialsync',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/initialsync.lazy').then((d) => d.Route))

const CollectionLazyRoute = CollectionLazyImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/collection.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionLazyImport
      parentRoute: typeof rootRoute
    }
    '/initialsync': {
      id: '/initialsync'
      path: '/initialsync'
      fullPath: '/initialsync'
      preLoaderRoute: typeof InitialsyncLazyImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/collection': typeof CollectionLazyRoute
  '/initialsync': typeof InitialsyncLazyRoute
  '/setup': typeof SetupLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/collection': typeof CollectionLazyRoute
  '/initialsync': typeof InitialsyncLazyRoute
  '/setup': typeof SetupLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/collection': typeof CollectionLazyRoute
  '/initialsync': typeof InitialsyncLazyRoute
  '/setup': typeof SetupLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection' | '/initialsync' | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/initialsync' | '/setup'
  id: '__root__' | '/' | '/collection' | '/initialsync' | '/setup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CollectionLazyRoute: typeof CollectionLazyRoute
  InitialsyncLazyRoute: typeof InitialsyncLazyRoute
  SetupLazyRoute: typeof SetupLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CollectionLazyRoute: CollectionLazyRoute,
  InitialsyncLazyRoute: InitialsyncLazyRoute,
  SetupLazyRoute: SetupLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/collection",
        "/initialsync",
        "/setup"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/collection": {
      "filePath": "collection.lazy.tsx"
    },
    "/initialsync": {
      "filePath": "initialsync.lazy.tsx"
    },
    "/setup": {
      "filePath": "setup.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
