/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const SetupLazyRouteImport = createFileRoute('/setup')()
const InitialsyncLazyRouteImport = createFileRoute('/initialsync')()
const CollectionLazyRouteImport = createFileRoute('/collection')()
const IndexLazyRouteImport = createFileRoute('/')()

const SetupLazyRoute = SetupLazyRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/setup.lazy').then((d) => d.Route))
const InitialsyncLazyRoute = InitialsyncLazyRouteImport.update({
  id: '/initialsync',
  path: '/initialsync',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/initialsync.lazy').then((d) => d.Route))
const CollectionLazyRoute = CollectionLazyRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/collection.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/collection': typeof CollectionLazyRoute
  '/initialsync': typeof InitialsyncLazyRoute
  '/setup': typeof SetupLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/collection': typeof CollectionLazyRoute
  '/initialsync': typeof InitialsyncLazyRoute
  '/setup': typeof SetupLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/collection': typeof CollectionLazyRoute
  '/initialsync': typeof InitialsyncLazyRoute
  '/setup': typeof SetupLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection' | '/initialsync' | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/initialsync' | '/setup'
  id: '__root__' | '/' | '/collection' | '/initialsync' | '/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CollectionLazyRoute: typeof CollectionLazyRoute
  InitialsyncLazyRoute: typeof InitialsyncLazyRoute
  SetupLazyRoute: typeof SetupLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialsync': {
      id: '/initialsync'
      path: '/initialsync'
      fullPath: '/initialsync'
      preLoaderRoute: typeof InitialsyncLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CollectionLazyRoute: CollectionLazyRoute,
  InitialsyncLazyRoute: InitialsyncLazyRoute,
  SetupLazyRoute: SetupLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
